
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class bill extends javax.swing.JFrame {

    private Object st;

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        tf_name_bill = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        tf_cost = new javax.swing.JTextField();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        tf_pay = new javax.swing.JTextField();
        javax.swing.JButton btn_add_bill = new javax.swing.JButton();
        javax.swing.JButton btn_clear_bill = new javax.swing.JButton();
        tf_con_bill = new javax.swing.JTextField();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JButton btn_add1 = new javax.swing.JButton();
        javax.swing.JButton btn_delete_bill = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        rf_sum_cost = new javax.swing.JTextField();
        rf_sum_pay = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        javax.swing.JButton btn_pat2 = new javax.swing.JButton();
        javax.swing.JButton btn_bill2 = new javax.swing.JButton();
        javax.swing.JButton btn_ser2 = new javax.swing.JButton();
        tf_search_cost = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JButton btn_search_cost = new javax.swing.JButton();
        javax.swing.JButton go_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(131, 169, 247));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tooth-٢.png"))); // NOI18N
        jLabel1.setText("Bills");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New bills", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 14), new java.awt.Color(57, 102, 207))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("NAME:");

        tf_name_bill.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("COST:");

        tf_cost.setForeground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("PAY:");

        tf_pay.setForeground(new java.awt.Color(51, 51, 51));

        btn_add_bill.setBackground(new java.awt.Color(255, 255, 255));
        btn_add_bill.setForeground(new java.awt.Color(0, 102, 204));
        btn_add_bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-١.png"))); // NOI18N
        btn_add_bill.setText("ADD");
        btn_add_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_billActionPerformed(evt);
            }
        });

        btn_clear_bill.setBackground(new java.awt.Color(255, 255, 255));
        btn_clear_bill.setForeground(new java.awt.Color(0, 102, 204));
        btn_clear_bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading-arrow.png"))); // NOI18N
        btn_clear_bill.setText("CLEAR");
        btn_clear_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_billActionPerformed(evt);
            }
        });

        tf_con_bill.setForeground(new java.awt.Color(51, 51, 51));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("condition:");

        btn_add1.setBackground(new java.awt.Color(255, 255, 255));
        btn_add1.setForeground(new java.awt.Color(0, 102, 204));
        btn_add1.setText("UPDATE");
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_add_bill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_clear_bill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_add1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_con_bill, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_pay, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_name_bill, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_cost, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_name_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_con_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_add_bill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btn_delete_bill.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete_bill.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_delete_bill.setForeground(new java.awt.Color(0, 102, 204));
        btn_delete_bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bin.png"))); // NOI18N
        btn_delete_bill.setText("DELETE");
        btn_delete_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_billActionPerformed(evt);
            }
        });

        Table2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_bill", "name", "condition", "date", "cost", "pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table2);

        jLabel16.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Smile Clinic ");

        rf_sum_cost.setForeground(new java.awt.Color(51, 51, 51));
        rf_sum_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rf_sum_costActionPerformed(evt);
            }
        });

        rf_sum_pay.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SUM OF COST:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SUM OF PAY:");

        jPanel7.setBackground(new java.awt.Color(99, 134, 242));

        btn_pat2.setBackground(new java.awt.Color(153, 180, 255));
        btn_pat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dental-report.png"))); // NOI18N
        btn_pat2.setBorderPainted(false);
        btn_pat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pat2ActionPerformed(evt);
            }
        });

        btn_bill2.setBackground(new java.awt.Color(153, 180, 255));
        btn_bill2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tooth-٢.png"))); // NOI18N
        btn_bill2.setBorderPainted(false);
        btn_bill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bill2ActionPerformed(evt);
            }
        });

        btn_ser2.setBackground(new java.awt.Color(153, 180, 255));
        btn_ser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tooth.png"))); // NOI18N
        btn_ser2.setBorderPainted(false);
        btn_ser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ser2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_pat2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_bill2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ser2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ser2)
                    .addComponent(btn_bill2)
                    .addComponent(btn_pat2))
                .addContainerGap())
        );

        tf_search_cost.setForeground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("search by id:");

        btn_search_cost.setBackground(new java.awt.Color(255, 255, 255));
        btn_search_cost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_search_cost.setForeground(new java.awt.Color(0, 102, 204));
        btn_search_cost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/feedback-search-١.png"))); // NOI18N
        btn_search_cost.setText("search");
        btn_search_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_costActionPerformed(evt);
            }
        });

        go_btn.setBackground(new java.awt.Color(255, 255, 255));
        go_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        go_btn.setForeground(new java.awt.Color(0, 102, 204));
        go_btn.setText("go");
        go_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btn_delete_bill)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_search_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_search_cost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rf_sum_cost, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(rf_sum_pay))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(go_btn)
                                .addGap(6, 6, 6)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel1))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rf_sum_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rf_sum_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_search_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_search_cost)
                                    .addComponent(btn_delete_bill)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(go_btn)))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_delete_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_billActionPerformed
        String id;
        int notFound=0;
        try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       String user="root";
       String password="";
       String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
       Connection con= DriverManager.getConnection(url, user, password);
       Statement st=con.createStatement();
       
       id= tf_search_cost.getText();
       
        if("".equals(id))
       {
           JOptionPane.showMessageDialog(new JFrame(),"id is require","Dialog", JOptionPane.ERROR_MESSAGE);
       }
        
        else 
        {
         String sql="SELECT * FROM bills WHERE id_bill="+id;
         ResultSet rs=st.executeQuery(sql);
         while(rs.next())
         {     
           notFound=1;
         String sql2="DELETE FROM bills WHERE id_bill="+id;
         st.executeUpdate(sql2);
           con.close();
           loadData();
         } 
         if(notFound==0)
         {
              JOptionPane.showMessageDialog(new JFrame(),"id not found","Dialog", JOptionPane.ERROR_MESSAGE);
         }
        }
        
       }
       catch (SQLException e) {
    e.printStackTrace();
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        } 
                                            

    }//GEN-LAST:event_btn_delete_billActionPerformed

    private void btn_pat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pat2ActionPerformed
        mainframe ob3=new mainframe();
        ob3.setVisible(true);
    }//GEN-LAST:event_btn_pat2ActionPerformed

    private void btn_bill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bill2ActionPerformed
       
    }//GEN-LAST:event_btn_bill2ActionPerformed

    private void btn_ser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ser2ActionPerformed
        serviece ob4=new serviece();
        ob4.setVisible(true);
    }//GEN-LAST:event_btn_ser2ActionPerformed

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        String id;
        String n,c,co,pa;
        int notFound=0;
        try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       String user="root";
       String password="";
       String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
       Connection con= DriverManager.getConnection(url, user, password);
       Statement st=con.createStatement();
       
       id= tf_search_cost.getText();
       
        if("".equals(id))
       {
           JOptionPane.showMessageDialog(new JFrame(),"id is require","Dialog", JOptionPane.ERROR_MESSAGE);
       }
        
        else 
        {
         String sql="SELECT * FROM bills WHERE id_bill="+id;
         ResultSet rs=st.executeQuery(sql);
         while(rs.next())
         {     
            notFound=1;
            n=tf_name_bill.getText();
            c=tf_con_bill.getText();
            co= tf_cost.getText();
            pa=tf_pay.getText();
            
         String sql2="UPDATE  bills SET name_patient_B='"+n+"',condition_t='"+c+ "',cost='"+co+"',pay='"+pa+"' WHERE id_bill="+id;
         st.executeUpdate(sql2);
         con.close();
         loadData();
         } 
         if(notFound==0)
         {
              JOptionPane.showMessageDialog(new JFrame(),"id not found","Dialog", JOptionPane.ERROR_MESSAGE);
         }
        }
        
       }
       catch (SQLException e) {
    e.printStackTrace();
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void btn_search_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_costActionPerformed
        String id;
        int notFound=0;
        try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       String user="root";
       String password="";
       String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
       Connection con= DriverManager.getConnection(url, user, password);
       Statement st=con.createStatement();
       
       id= tf_search_cost.getText();
       
        if("".equals(id))
       {
           JOptionPane.showMessageDialog(new JFrame(),"id is require","Dialog", JOptionPane.ERROR_MESSAGE);
       }
        
        else 
        {
         String sql="SELECT * FROM bills WHERE id_bill="+id;
         ResultSet rs=st.executeQuery(sql);
         while(rs.next())
         {  
            
           tf_name_bill.setText(rs.getString("name_patient_B"));
           tf_con_bill.setText(rs.getString("condition_t"));
           tf_cost.setText(rs.getString("cost"));
           tf_pay.setText(rs.getString("pay"));
           
           notFound=1;
           con.close();
    

         } 
         if(notFound==0)
         {
              JOptionPane.showMessageDialog(new JFrame(),"id not found","Dialog", JOptionPane.ERROR_MESSAGE);
         }
        }
        
       }
       catch (SQLException e) {
    e.printStackTrace();
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_search_costActionPerformed

    
    
        public  void loadData() throws ClassNotFoundException, SQLException
    {
    try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       String user="root";
       String password="";
       String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
       Connection con= DriverManager.getConnection(url, user, password);
       Statement st=con.createStatement();
       DefaultTableModel model=new  DefaultTableModel(new String[]{"id_bill","name","condition","date","cost","pay"},0);
       
       Table2.setModel(model);
       String sql="SELECT * FROM bills";
       ResultSet rs=st.executeQuery(sql);
       String i_b,n,c,d,co,pa;
       while(rs.next())
       {
         i_b=rs.getString("id_bill");
         n=rs.getString("name_patient_B");
         c=rs.getString("condition_t");
         d=rs.getString("date");
         co=rs.getString("cost");
         pa=rs.getString("pay");
        
         model.addRow(new Object[]{i_b,n,c,d,co,pa});
       }
    }//!!!!!!!!!!!!1
        catch(Exception e)
        {
            System.out.println("erorr)"+e.getMessage()); 
        }
    }
    private void btn_add_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_billActionPerformed
        String name;
        String condition_t;
        String cost;
        String pay;
        String query;
        //connect to database
        try
        { 
            Class.forName("com.mysql.cj.jdbc.Driver");
        String user="root";
        String password="";
        String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
        Connection con= DriverManager.getConnection(url, user, password);
        Statement st=con.createStatement();
       if("".equals(tf_name_bill.getText()))
       {
           JOptionPane.showMessageDialog(new JFrame(),"name is require","Dialog", JOptionPane.ERROR_MESSAGE);
        }
     
     
         else  if("".equals(tf_con_bill.getText()))
       {
           JOptionPane.showMessageDialog(new JFrame(),"condition is require","Dialog", JOptionPane.ERROR_MESSAGE);
        }
         else  if("".equals(tf_cost.getText()))
       {
           JOptionPane.showMessageDialog(new JFrame(),"cost is require","Dialog", JOptionPane.ERROR_MESSAGE);
        }
           else  if("".equals(tf_pay.getText()))
       {
           JOptionPane.showMessageDialog(new JFrame(),"pay is require","Dialog", JOptionPane.ERROR_MESSAGE);
        }
         else{
             
        name=tf_name_bill.getText();
        condition_t=tf_con_bill.getText();
        cost=tf_cost.getText();
        pay=tf_pay.getText();
        
         // 1. تعريف جملة الـ SQL مع استخدام علامات الاستفهام كـ Placeholders
           query = "INSERT INTO bills ( name_patient_B , condition_t , cost ,pay) VALUES (?, ?, ?, ?)";

try (PreparedStatement pstmt = con.prepareStatement(query)) {
    // 2. تعبئة البيانات بترتيب علامات الاستفهام
    pstmt.setString(1, name);
    pstmt.setString(2, condition_t);
    pstmt.setString(3, cost);      // افترضنا أن السن رقم (int)
    pstmt.setString(4, pay);

    // 3. تنفيذ التحديث
    pstmt.executeUpdate();
    
    JOptionPane.showMessageDialog(new JFrame(),"done  successfully","Dialog", JOptionPane.DEFAULT_OPTION);
       
    con.close();
    loadData();
} catch (SQLException e) {
    e.printStackTrace();
}
         }
     
     
     
         
        }
        catch(Exception e)
        {
            System.out.println("erorr)"+e.getMessage()); 
        }
                                           

    }//GEN-LAST:event_btn_add_billActionPerformed

    private void btn_clear_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_billActionPerformed
        tf_name_bill.setText("");
        tf_con_bill.setText("");
        tf_cost.setText("");
        tf_pay.setText("");
        tf_search_cost.setText("");
        rf_sum_cost.setText("");
        rf_sum_pay.setText("");
    }//GEN-LAST:event_btn_clear_billActionPerformed

    private void rf_sum_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rf_sum_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rf_sum_costActionPerformed

    private void go_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_btnActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
       String user="root";
       String password="";
       String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
       Connection con= DriverManager.getConnection(url, user, password);
       Statement st=con.createStatement();  
            
    String sql = "SELECT SUM(cost) AS total_cost, SUM(pay) AS total_pay FROM bills";
    ResultSet rs = st.executeQuery(sql);

    // التحرك إلى الصف الأول (مهم جداً!)
    if (rs.next()) {
        // نستخدم الاسم المستعار "total_cost" الذي حددناه في الاستعلام
        String sumCost = rs.getString("total_cost");
        rf_sum_cost.setText(sumCost);
        
        
        String sumPay = rs.getString("total_pay");
        rf_sum_pay.setText(sumPay);
    }
} catch (SQLException e) {
    e.printStackTrace(); // لطباعة أي خطأ في الاتصال أو الاستعلام
}
         catch(Exception e)
        {
            System.out.println("erorr)"+e.getMessage()); 
        }
    }//GEN-LAST:event_go_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
                  bill x=new bill();
                try {
                    x.loadData();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
                }
                x.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField rf_sum_cost;
    private javax.swing.JTextField rf_sum_pay;
    private javax.swing.JTextField tf_con_bill;
    private javax.swing.JTextField tf_cost;
    private javax.swing.JTextField tf_name_bill;
    private javax.swing.JTextField tf_pay;
    private javax.swing.JTextField tf_search_cost;
    // End of variables declaration//GEN-END:variables
}
