
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class serviece extends javax.swing.JFrame {

    /**
     * Creates new form serviece
     */
    public serviece() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        tf_name_ser = new javax.swing.JTextField();
        javax.swing.JButton btn_add_ser = new javax.swing.JButton();
        javax.swing.JButton btn_clear_ser = new javax.swing.JButton();
        tf_price_ser = new javax.swing.JTextField();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JButton btn_add1 = new javax.swing.JButton();
        javax.swing.JButton btn_delete_ser = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        Table3 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        javax.swing.JButton btn_pat3 = new javax.swing.JButton();
        javax.swing.JButton btn_bill3 = new javax.swing.JButton();
        javax.swing.JButton btn_ser3 = new javax.swing.JButton();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        tf_search_ser = new javax.swing.JTextField();
        javax.swing.JButton btn_search_ser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(174, 190, 248));

        jLabel16.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Smile Clinic ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tooth.png"))); // NOI18N
        jLabel1.setText("services");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New service", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 14), new java.awt.Color(57, 102, 207))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("NAME SERVICE:");

        tf_name_ser.setForeground(new java.awt.Color(51, 51, 51));

        btn_add_ser.setBackground(new java.awt.Color(255, 255, 255));
        btn_add_ser.setForeground(new java.awt.Color(0, 102, 204));
        btn_add_ser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-١.png"))); // NOI18N
        btn_add_ser.setText("ADD");
        btn_add_ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_serActionPerformed(evt);
            }
        });

        btn_clear_ser.setBackground(new java.awt.Color(255, 255, 255));
        btn_clear_ser.setForeground(new java.awt.Color(0, 102, 204));
        btn_clear_ser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading-arrow.png"))); // NOI18N
        btn_clear_ser.setText("CLEAR");
        btn_clear_ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_serActionPerformed(evt);
            }
        });

        tf_price_ser.setForeground(new java.awt.Color(51, 51, 51));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("PRICE SERVICE:");

        btn_add1.setBackground(new java.awt.Color(255, 255, 255));
        btn_add1.setForeground(new java.awt.Color(0, 102, 204));
        btn_add1.setText("UPDATE");
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_add_ser)
                        .addGap(32, 32, 32)
                        .addComponent(btn_add1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_clear_ser)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_name_ser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(tf_price_ser, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_name_ser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_price_ser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_ser)
                    .addComponent(btn_clear_ser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_delete_ser.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete_ser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_delete_ser.setForeground(new java.awt.Color(0, 102, 204));
        btn_delete_ser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bin.png"))); // NOI18N
        btn_delete_ser.setText("DELETE");
        btn_delete_ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_serActionPerformed(evt);
            }
        });

        Table3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_service", "name_service", "price_service"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table3);

        jPanel4.setBackground(new java.awt.Color(114, 134, 239));

        btn_pat3.setBackground(new java.awt.Color(204, 204, 255));
        btn_pat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dental-report.png"))); // NOI18N
        btn_pat3.setBorderPainted(false);
        btn_pat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pat3ActionPerformed(evt);
            }
        });

        btn_bill3.setBackground(new java.awt.Color(204, 204, 255));
        btn_bill3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tooth-٢.png"))); // NOI18N
        btn_bill3.setBorderPainted(false);
        btn_bill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bill3ActionPerformed(evt);
            }
        });

        btn_ser3.setBackground(new java.awt.Color(204, 204, 255));
        btn_ser3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tooth.png"))); // NOI18N
        btn_ser3.setBorderPainted(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_pat3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btn_bill3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ser3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ser3)
                    .addComponent(btn_bill3)
                    .addComponent(btn_pat3))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("search by id:");

        tf_search_ser.setForeground(new java.awt.Color(51, 51, 51));

        btn_search_ser.setBackground(new java.awt.Color(255, 255, 255));
        btn_search_ser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_search_ser.setForeground(new java.awt.Color(0, 102, 204));
        btn_search_ser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/feedback-search-١.png"))); // NOI18N
        btn_search_ser.setText("search");
        btn_search_ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_serActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_search_ser, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_search_ser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_delete_ser)
                        .addGap(25, 25, 25)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel12)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_ser)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_search_ser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_search_ser)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_delete_serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_serActionPerformed
        String id;
        int notFound=0;
        try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       String user="root";
       String password="";
       String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
       Connection con= DriverManager.getConnection(url, user, password);
       Statement st=con.createStatement();
       
       id= tf_search_ser.getText();
       
        if("".equals(id))
       {
           JOptionPane.showMessageDialog(new JFrame(),"id is require","Dialog", JOptionPane.ERROR_MESSAGE);
       }
        
        else 
        {
         String sql="SELECT * FROM services WHERE id_service="+id;
         ResultSet rs=st.executeQuery(sql);
         while(rs.next())
         {     
           notFound=1;
         String sql2="DELETE FROM services WHERE id_service="+id;
         st.executeUpdate(sql2);
           con.close();
           loadData();
         } 
         if(notFound==0)
         {
              JOptionPane.showMessageDialog(new JFrame(),"id not found","Dialog", JOptionPane.ERROR_MESSAGE);
         }
        }
        
       }
       catch (SQLException e) {
    e.printStackTrace();
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        } 
                                            

    }//GEN-LAST:event_btn_delete_serActionPerformed

    private void btn_pat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pat3ActionPerformed
       mainframe ob5=new mainframe();
       ob5.setVisible(true);
    }//GEN-LAST:event_btn_pat3ActionPerformed

    private void btn_bill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bill3ActionPerformed
       bill ob6=new bill();
       ob6.setVisible(true);
    }//GEN-LAST:event_btn_bill3ActionPerformed

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        String id;
        String n_s,p_s;
        int notFound=0;
        try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       String user="root";
       String password="";
       String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
       Connection con= DriverManager.getConnection(url, user, password);
       Statement st=con.createStatement();
       
       id= tf_search_ser.getText();
       
        if("".equals(id))
       {
           JOptionPane.showMessageDialog(new JFrame(),"id is require","Dialog", JOptionPane.ERROR_MESSAGE);
       }
        
        else 
        {
         String sql="SELECT * FROM services WHERE id_service="+id;
         ResultSet rs=st.executeQuery(sql);
         while(rs.next())
         {     
            notFound=1;
            n_s=tf_name_ser.getText();
            p_s=tf_price_ser.getText();
          
            
         String sql2="UPDATE  services SET name_service='"+n_s+"',price_service='"+p_s+ "' WHERE id_service="+id;
         st.executeUpdate(sql2);
         con.close();
         loadData();
         } 
         if(notFound==0)
         {
              JOptionPane.showMessageDialog(new JFrame(),"id not found","Dialog", JOptionPane.ERROR_MESSAGE);
         }
        }
        
       }
       catch (SQLException e) {
    e.printStackTrace();
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void btn_search_serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_serActionPerformed
        String id;
        int notFound=0;
        try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       String user="root";
       String password="";
       String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
       Connection con= DriverManager.getConnection(url, user, password);
       Statement st=con.createStatement();
       
       id= tf_search_ser.getText();
       
        if("".equals(id))
       {
           JOptionPane.showMessageDialog(new JFrame(),"id is require","Dialog", JOptionPane.ERROR_MESSAGE);
       }
        
        else 
        {
         String sql="SELECT * FROM services WHERE id_service="+id;
         ResultSet rs=st.executeQuery(sql);
         while(rs.next())
         {  
            
           tf_name_ser.setText(rs.getString("name_service"));
           tf_price_ser.setText(rs.getString("price_service"));
         
           
           notFound=1;
           con.close();
    

         } 
         if(notFound==0)
         {
              JOptionPane.showMessageDialog(new JFrame(),"id not found","Dialog", JOptionPane.ERROR_MESSAGE);
         }
        }
        
       }
       catch (SQLException e) {
    e.printStackTrace();
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_search_serActionPerformed

    
    
        public  void loadData() throws ClassNotFoundException, SQLException
    {
    try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       String user="root";
       String password="";
       String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
       Connection con= DriverManager.getConnection(url, user, password);
       Statement st=con.createStatement();
       DefaultTableModel model=new  DefaultTableModel(new String[]{"id_service","name_service","price_service",},0);
       
       Table3.setModel(model);
       String sql="SELECT * FROM services";
       ResultSet rs=st.executeQuery(sql);
       String i_s,n_s,p_s;
       while(rs.next())
       {
         i_s=rs.getString("id_service");
         n_s=rs.getString("name_service");
         p_s=rs.getString("price_service");
         
        
         model.addRow(new Object[]{i_s,n_s,p_s});
       }
    }//!!!!!!!!!!!!1
        catch(Exception e)
        {
            System.out.println("erorr)"+e.getMessage()); 
        }
    }
    
    private void btn_add_serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_serActionPerformed
        String name;
        String price;
        String query;
        //connect to database
        try
        { 
            Class.forName("com.mysql.cj.jdbc.Driver");
        String user="root";
        String password="";
        String url="jdbc:mysql://127.0.0.1:3306/smile_clinc";
        Connection con= DriverManager.getConnection(url, user, password);
        Statement st=con.createStatement();
       if("".equals(tf_name_ser.getText()))
       {
           JOptionPane.showMessageDialog(new JFrame(),"name service is require","Dialog", JOptionPane.ERROR_MESSAGE);
        }
     
     
         else  if("".equals(tf_price_ser.getText()))
       {
           JOptionPane.showMessageDialog(new JFrame(),"price is require","Dialog", JOptionPane.ERROR_MESSAGE);
        }
      
         else{
             
        name=tf_name_ser.getText();
        price=tf_price_ser.getText();
        
        
         // 1. تعريف جملة الـ SQL مع استخدام علامات الاستفهام كـ Placeholders
           query = "INSERT INTO services ( name_service, price_service) VALUES (?, ?)";

try (PreparedStatement pstmt = con.prepareStatement(query)) {
    // 2. تعبئة البيانات بترتيب علامات الاستفهام
    pstmt.setString(1, name);
    pstmt.setString(2, price);
 
    // 3. تنفيذ التحديث
    pstmt.executeUpdate();
    
    JOptionPane.showMessageDialog(new JFrame(),"done  successfully","Dialog", JOptionPane.DEFAULT_OPTION);
       
    con.close();
    loadData();
} catch (SQLException e) {
    e.printStackTrace();
}
         }
     
     
     
         
        }
        catch(Exception e)
        {
            System.out.println("erorr)"+e.getMessage()); 
        }
                                           

    }//GEN-LAST:event_btn_add_serActionPerformed

    private void btn_clear_serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_serActionPerformed
        tf_name_ser.setText("");
        tf_price_ser.setText("");
        tf_search_ser.setText("");
    }//GEN-LAST:event_btn_clear_serActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serviece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serviece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serviece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serviece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                  serviece x=new serviece();
                try {
                    x.loadData();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
                }
                x.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField tf_name_ser;
    private javax.swing.JTextField tf_price_ser;
    private javax.swing.JTextField tf_search_ser;
    // End of variables declaration//GEN-END:variables
}
